export const GAME_CONFIG = {
  arena: 3000,
  maxFrameDelta: 34,
  initialCoreHp: 3,
  initialSegments: 3,
  maxSegments: 44,
  segmentGap: 13,
  baseSpeed: 188,
  baseTurnRate: 7.2,
  turnRateDecay: 0.072,
  turnRateFloor: 4.35,
  inputDeadZone: 7,
  joystickRadius: 42,
  joystickFollowRadius: 54,
  headRadius: 17,
  bodyRadius: 13,
  magnetRadius: 112,
  invulnMs: 1100,
  lethalProtectionMs: 30000,
  buildPauseCooldownMs: 650,
  foodSpawnMs: 680,
  skillFirstDropMs: 12000,
  skillDropMs: 30000,
  skillDropMinMs: 15000,
  skillDropJitterMs: 6500,
  skillDropKillAccelMs: 850,
  skillDropKillAccelMaxMs: 9500,
  skillDropPityKills: 11,
  minUpgradeGapMs: 26000,
  queuedUpgradeDangerHoldMs: 9000,
  enemySpawnMs: 1180,
  bossSpawnMs: 120000,
  bossSpawnKills: 48,
  bossHp: 360,
  bossShieldWeakpoints: 3,
  bodyCrackLimit: 3,
  bodyHitCooldownMs: 760,
  firstEventMs: 18000,
  waveEventMs: 28000,
  waveEventDurationMs: 9000,
  settlementHardCapMs: 20000,
};

export const GROWTH_STAGES = [
  { id: "hatchling", name: "幼蛇", at: 3, text: "轻快、短小，命门清楚。" },
  { id: "ring", name: "环蛇", at: 8, text: "身体开始形成战斗半径，磁吸增强。" },
  { id: "spine", name: "脊蛇", at: 16, text: "技能节点增多，转向压力上升。" },
  { id: "array", name: "阵蛇", at: 24, text: "身体变成移动阵地，格挡收益变高。" },
  { id: "final_molt", name: "终蜕", at: 34, text: "记忆接近满载，稀有事件开始出现。" },
  { id: "overload", name: "贪满", at: 44, text: "身体不再增长，额外记忆会转为过载。" },
];

export const CHAPTERS = [
  {
    id: "hatchery",
    name: "一章：孵梦回廊",
    shortName: "孵梦",
    startMs: 0,
    color: 0xffb238,
    text: "熟悉移动、吞噬记忆，第一次把身体变成武器。",
  },
  {
    id: "archive",
    name: "二章：暗金档案",
    shortName: "档案",
    startMs: 120000,
    color: 0x36e89f,
    text: "敌群变密，精英开始干扰路线，构筑必须成形。",
  },
  {
    id: "molt",
    name: "三章：绯红蜕场",
    shortName: "蜕场",
    startMs: 270000,
    color: 0xff5f91,
    text: "怪潮和 Boss 弹幕压缩空间，长身体既是火力也是负担。",
  },
  {
    id: "throne",
    name: "终章：蛇祀王座",
    shortName: "王座",
    startMs: 420000,
    color: 0x9d7dff,
    text: "所有技能组合进入终局压力测试，击败档案蛇像才算抵达结尾。",
  },
];

export const BOSS_STAGES = [
  {
    id: "memory_warden",
    name: "记忆典狱长",
    chapter: "archive",
    spawnMs: 115000,
    spawnKills: 44,
    hp: 260,
    radius: 58,
    speed: 74,
    shield: 2,
    color: 0x36e89f,
    projectileColor: 0x7ce6ff,
    texture: "boss-warden-v9",
    fallbackTexture: "boss-core-v5",
    pattern: "cross",
    rewardText: "典狱长碎裂，档案门第一次打开。",
  },
  {
    id: "crimson_molt",
    name: "绯红蜕王",
    chapter: "molt",
    spawnMs: 270000,
    spawnKills: 96,
    hp: 420,
    radius: 72,
    speed: 88,
    shield: 3,
    color: 0xff5f91,
    projectileColor: 0xff7043,
    texture: "boss-crimson-v9",
    fallbackTexture: "boss-core-v5",
    pattern: "fan",
    rewardText: "绯红旧皮脱落，蛇身短暂轻了下来。",
  },
  {
    id: "archivist_idol",
    name: "档案蛇像",
    chapter: "throne",
    spawnMs: 430000,
    spawnKills: 150,
    hp: 620,
    radius: 84,
    speed: 70,
    shield: 4,
    color: 0x9d7dff,
    projectileColor: 0xfff0b0,
    texture: "boss-archivist-v9",
    fallbackTexture: "boss-core-v5",
    pattern: "spiral",
    final: true,
    rewardText: "档案蛇像倒下，这条蛇终于写完了自己。",
  },
];

export const ELITE_EVENTS = [
  {
    id: "warden_patrol",
    name: "典狱巡行",
    chapter: "archive",
    minMs: 90000,
    color: 0x36e89f,
    text: "一队裂牙从记忆边缘包抄。",
  },
  {
    id: "crimson_surge",
    name: "绯红潮汐",
    chapter: "molt",
    minMs: 230000,
    color: 0xff5f91,
    text: "瘤核携带绯红孢群逼近蛇首。",
  },
  {
    id: "idol_edict",
    name: "蛇像敕令",
    chapter: "throne",
    minMs: 390000,
    color: 0x9d7dff,
    text: "全场敌影短暂共鸣，技能核掉落率提高。",
  },
];

export const RELIC_POOL = [
  {
    id: "ember_gland",
    name: "余烬腺体",
    icon: "烬",
    text: "火焰光环等级 +1，并让下一次火焰爆发范围更大。",
    theme: "flame",
  },
  {
    id: "cold_blood",
    name: "冷血心脏",
    icon: "寒",
    text: "冰冻轨迹等级 +1；身体裂痕减少 1。",
    theme: "frost",
  },
  {
    id: "broken_tail",
    name: "断尾本能",
    icon: "尾",
    text: "立即失去 3 节身体，回复 1 心，获得一次稀有技能核。",
    theme: "guard",
  },
  {
    id: "magnetic_scales",
    name: "磁化鳞片",
    icon: "磁",
    text: "磁吸范围永久增强，但围猎潮更容易出现。",
    theme: "tech",
  },
  {
    id: "storm_vertebra",
    name: "雷脊骨",
    icon: "脊",
    text: "闪电链等级 +1，Boss 弱点命中伤害提高。",
    theme: "voltage",
  },
];

export const SURPRISE_EVENTS = [
  {
    id: "double_core",
    name: "双生技能核",
    icon: "双",
    text: "连续选择两张技能牌，但身体裂痕 +1。",
    rarity: "rare",
  },
  {
    id: "greed_gate",
    name: "贪婪门",
    icon: "门",
    text: "立刻生成大量记忆，同时触发一波围猎潮。",
    rarity: "rare",
  },
  {
    id: "boss_echo",
    name: "Boss 回声",
    icon: "影",
    text: "提前显现一枚 Boss 弱点幻影；击碎后获得过载记忆。",
    rarity: "rare",
  },
  {
    id: "safe_void",
    name: "空白安全区",
    icon: "空",
    text: "清空附近敌人，但下一次事件更危险。",
    rarity: "uncommon",
  },
];

export const COLORS = {
  ink: 0x05070b,
  abyss: 0x080b0d,
  panel: 0x101820,
  line: 0x274152,
  cyan: 0x61efff,
  playerShot: 0x9af7ff,
  enemyShot: 0xff4a28,
  dangerCore: 0xfff0b0,
  acid: 0xa7ff65,
  gold: 0xffd166,
  reward: 0xffb238,
  jade: 0x36e89f,
  ember: 0xff7043,
  frost: 0x7ce6ff,
  rose: 0xff5f91,
  violet: 0x9d7dff,
  red: 0xff3b4f,
  white: 0xf4fbff,
  slate: 0x8da0a8,
};

export const SKILLS = [
  {
    id: "fire",
    name: "龙息火舌",
    icon: "火",
    theme: "flame",
    iconFile: "fire_flame.png",
    cost: 2,
    text: "蛇首向前喷出短促火舌，近身清怪强，升级后变宽变久。",
  },
  {
    id: "frost",
    name: "冰冻轨迹",
    icon: "冰",
    theme: "frost",
    iconFile: "ice_crystal.png",
    cost: 2,
    text: "尾迹留下冰痕，怪潮踩上后减速并碎裂。",
  },
  {
    id: "turret",
    name: "尖牙弹",
    icon: "牙",
    theme: "tech",
    iconFile: "fang_projectile.png",
    cost: 3,
    text: "从蛇口与前身射出尖牙，单点追踪，适合打精英和 Boss。",
  },
  {
    id: "spear",
    name: "穿刺圣矛",
    icon: "矛",
    theme: "spear",
    iconFile: "piercing_spear.png",
    cost: 4,
    text: "凝出一束长矛贯穿直线敌群，伤害高但间隔更长。",
  },
  {
    id: "magnet",
    name: "记忆磁场",
    icon: "吸",
    theme: "memory",
    iconFile: "memory_magnet.png",
    cost: 2,
    text: "扩大记忆吸附范围，拾取时产生清晰的宝石回流。",
  },
  {
    id: "speed",
    name: "疾行蜕影",
    icon: "速",
    theme: "wind",
    iconFile: "serpent_speed.png",
    cost: 2,
    text: "提升移动和转向响应，身后留下短暂拖影。",
  },
  {
    id: "shield",
    name: "护身星轨",
    icon: "盾",
    theme: "guard",
    iconFile: "guardian_orbit.png",
    cost: 3,
    text: "护符绕前身巡行，削弱碰撞损失并反震贴身敌人。",
  },
  {
    id: "lightning",
    name: "闪电链",
    icon: "雷",
    theme: "voltage",
    iconFile: "chain_lightning.png",
    cost: 4,
    text: "电荷先沿骨节奔跑，再跳向敌人弱点。",
  },
];

export const ENEMY_KINDS = {
  drifter: { name: "饥影", hp: 2, radius: 18, speed: 92, score: 18 },
  hunter: { name: "裂牙", hp: 4, radius: 21, speed: 128, score: 36 },
  bloomer: { name: "瘤核", hp: 7, radius: 26, speed: 72, score: 64 },
  sentinel: { name: "典狱卫", hp: 12, radius: 30, speed: 96, score: 110 },
};

export const LIFE_TEMPLATES = [
  {
    cause: "greed",
    theme: "flame",
    text: "它生来只有三颗心，却把每一次吞噬都当成火种。第{stage}波时，{combo}照亮了半个巢穴；可它仍把头探向更深处。最终，贪婪没有熄灭它，只是把它烧成了一段被记住的蛇生。",
  },
  {
    cause: "greed",
    theme: "frost",
    text: "这条蛇沿着自己的冰痕前行，越长越安静，也越不肯回头。它在第{stage}波拾起{memory}，又为了下一枚记忆越过安全线。死亡来得很轻，像霜落在蛇首上。",
  },
  {
    cause: "greed",
    theme: "tech",
    text: "炮火替它开路，弹跳的光点替它计算风险。可它最后一次选择不是计算，而是多吃一口。第{stage}波后，{combo}仍在回响，它却已经把命门交给了怪潮。",
  },
  {
    cause: "swarmed",
    theme: "guard",
    text: "它曾用旋转的盾守住蛇首，也用身体替世界划出边界。第{stage}波时，怪潮从四面合拢，它没有后退，只把最后一段记忆护在身后。沉默之后，鳞光仍慢慢亮起。",
  },
  {
    cause: "swarmed",
    theme: "voltage",
    text: "电光在它的脊骨上奔跑，像一串不肯断开的念头。它击碎了{kills}只敌影，却没能在第{stage}波找到空隙。最后的闪电没有杀敌，只照见了它曾经走过的弯路。",
  },
  {
    cause: "boss",
    theme: "flame",
    text: "它终于抵达终点 Boss 面前，火环绕身，记忆如炭。那一战里，{combo}短暂撕开了巨影。可三颗心终有尽头，它倒下时没有退缩，只把一生烧成了最后的光。",
  },
  {
    cause: "boss",
    theme: "frost",
    text: "Boss 的影子压住了巢穴，它却用冰痕一寸寸量过战场。第{stage}波之后，{memory}还挂在蛇身中段。它没能通关，但死亡很干净，像一条冻结的归路。",
  },
  {
    cause: "boss",
    theme: "tech",
    text: "它带着炮台和电弧闯到终点，把自己的身体排成一座移动阵地。Boss 还剩{bossHp}%生命时，蛇首被击中。胜利只差一点，于是遗憾也显得格外锋利。",
  },
  {
    cause: "victory",
    theme: "guard",
    text: "这条蛇没有把贪婪交给深渊。它用护盾守住三颗心，用长身记下每一次选择，最终穿过 Boss 的残影。结局安静落下时，它不是怪物，而是一段完整走完的蛇生。",
  },
  {
    cause: "victory",
    theme: "voltage",
    text: "它把闪电藏进骨节，把每一次吞噬变成下一次前进。终点 Boss 倒下时，第{stage}波的回声仍在远处。它活着抵达结尾，却依旧安静，因为一生从不因胜利而变轻。",
  },
  {
    cause: "timeout",
    theme: "flame",
    text: "它在火光、冰雾与怪潮之间撑得太久，久到巢穴都开始记住它的路径。第{stage}波后，蛇身已近极限。死亡不是突然来临，而是这段贪婪终于写完了最后一行。",
  },
  {
    cause: "default",
    theme: "default",
    text: "这条蛇吃下{memory}，长出新的身体，也长出新的风险。它击碎{kills}只敌影，在第{stage}波停下。没有人能说它失败，因为每一节发光的身体，都曾是它认真活过的证据。",
  },
];

export const MEMORY_LINES = [
  "第一枚记忆在蛇首后方亮起。",
  "它学会了用身体承载火力。",
  "一段冰冷的尾迹留在怪潮中。",
  "炮台在蛇身中段醒来。",
  "护盾绕着命门旋转。",
  "闪电从一节身体跳向下一节。",
  "它曾在危险区多贪了一口。",
  "它听见 Boss 从巢穴深处回应。",
  "它差一点就选择回头。",
  "最后一颗心跳得很轻。",
];
